### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by awesomegamergame** [rcelyte/BeatUpRcelyte#1]
How do you build and run this server? because i want to test it but there is no documentation or anything that says how to build it.

**Comment by rcelyte** [comment]
As stated at the top of the readme, this project is not yet ready for public use. I will work on documentation closer to release, once the server is stable and not likely to change significantly. As for building, just run `make` in the cloned repository. Note that the server currently requires a valid SSL certificate to start.

**Comment by awesomegamergame** [comment]
Does this not work on windows because the make command doesnt exist

**Comment by rcelyte** [comment]
For Windows, use the Mingw-w64 toolchain.

**Comment by rcelyte** [comment]
@CaiB I know you're here, and I've heard your complaints about Make and Cmake before. I can't provide other options, since I need to compile the Mbed TLS source alongside mine. If you're unhappy, go ask them to support 3 build systems without Python and Perl helper scripts.

**Comment by CaiB** [comment]
MSYS has caused significant problems with my system before, and I'd never install it outside of a throwaway VM anymore. Definitely wouldn't ask someone else to use it.
