### ISSUE TITLE
Add timestamp with status updates

### ISSUE THREAD

**Issue by jabberjabberjabber** [rcelyte/BeatUpRcelyte#10]
For beatupserver updates to stdout

Instead of:

`[internal.c] (HTTP,bssb): /`

Could we have:

`<YYYYMMDD-HHMMSS> [internal.c] (HTTP,bssb): /`

or something similar?

It would be useful since I am piping this output to a file to use for logs.

Thanks.

**Comment by rcelyte** [comment]
Timestamps can be injected into any pipe without involving the application itself; See [this StackExchange question](https://unix.stackexchange.com/questions/26728/prepending-a-timestamp-to-each-line-of-output-from-a-command) for a few options on how to do that. Additionaly, many init daemons will prepend their own timestamps to service logs, making such a feature redundant.
