### ISSUE TITLE
Feature request: Server join message

### ISSUE THREAD

**Issue by jabberjabberjabber** [rcelyte/BeatUpRcelyte#19]
I would personally gain a lot of utility on my server if there were a configurable message that pops up once when new players join, or it could be triggered by some other one-time-event. It doesn't need to be more than 100 - 200 characters.  

The reasoning is that it seems people don't read (or aren't able to read?) the name of the instance when they join and get upset when they realize that others do not share their preferred style even though the map styles that are played are specifically named as the name of the lobby. 

Or, if the server name could be floating in the lobby somewhere all the time that would be useful enough.

I thank you for you consideration.

**Comment by rcelyte** [comment]
also the "server name" I'm pretty sure you're referring to is a feature of the client-side Server Browser mod, and not information the server has access to. If you want your Server Browser name presented to Server Browser users, that would be a feature request for https://github.com/roydejong/BeatSaberServerBrowser

**Comment by jabberjabberjabber** [comment]
Oh well. 

I haven't tried any of the recent MPChat builds but I will give it a go and see if it works.

> If you want your Server Browser name presented to Server Browser users, that would be a feature request

The only people who would join my server would do it from manually adding it or seeing it on server browser. I didn't know that name was dependent on server browser. Can you not create a name lobby in the normal multiplayer? What is up with this game in its unmodded state completely missing basic features that were standardized back with Quakeworld in 1996?

**Comment by rcelyte** [comment]
> this game in its unmodded state completely missing basic features that were standardized back with Quakeworld in 1996?

You're only realizing that now? 😛
