### ISSUE TITLE
Player connected and then unable to play

### ISSUE THREAD

**Issue by jabberjabberjabber** [rcelyte/BeatUpRcelyte#25]
beatupserver instance (not sure how to find version number but it was built on sept 9) one player (me) was connected and it allowed another player to join and when the player appeared they had a strange character in front the name entry on player board (looked like a p) followed by a space. Map was chosen but second player's name was unselectable and 'start' button could not be clicked. Second player looked confused then disconnected. Relevant server log section attached.
[beatupserver_2023_12_16.log](https://github.com/rcelyte/BeatUpRcelyte/files/13692210/beatupserver_2023_12_16.log)

**Comment by rcelyte** [comment]
That log doesn't show anything out of the ordinary, so I suspect the issue is client-side. Could you post your game log (and the other player's if possible)?

**Comment by jabberjabberjabber** [comment]
I only have mine; the other player is not someone I know. I sent it to you on discord.

**Comment by rcelyte** [comment]
I unfortunately can't do much without seeing the other player's log. Their game seems to be what's broken.

**Comment by jabberjabberjabber** [comment]
Thanks for the information. Glad it wasn't a server issue.
