### ISSUE TITLE
Start not possible

### ISSUE THREAD

**Issue by jabberjabberjabber** [rcelyte/BeatUpRcelyte#26]
Ran into an issue twice today where someone joined, the map ended, and then the 'start' button was greyed out. Unable to affect change by changing a new map or doing anything else. Left and created new server and it worked again.

I sent you the relevant logs in discord.

**Comment by rcelyte** [comment]
Please update your instance. I can't provide support for outdated versions of the server.

**Comment by jabberjabberjabber** [comment]
Sorry to be unclear, but I wasn't asking for support, I was informing you of an issue. I haven't upgraded since everything has been working and everyone has been on 1.29 consistently.

**Comment by jabberjabberjabber** [comment]
Issue turned out to be not related to Beatupserver.
