### ISSUE TITLE
Unable to use IPv4 on Windows

### ISSUE THREAD

**Issue by alsdzx** [rcelyte/BeatUpRcelyte#29]
I am unable to bind IPv4 TCP on Windows and can only bind IPv6 ports, even when using beatupserver --ipv4

[net.c] Bound 0.0.0.0:2328
[wire.c] TODO: remote wire
[master_local.c] Started
[net.c] block
[net.c] Bound 0.0.0.0:8106
[status_ssl.c] Started HTTP
[pool.c] pool_host_attach()
[instance.c] Started
Press [enter] to exit

**Comment by alsdzx** [comment]
The program compiled using Linux for cross-compilation can open IPv4 TCP port normally, while the program compiled using Windows MSYS2 for cross-compilation cannot function properly

**Comment by rcelyte** [comment]
> I am unable to bind IPv4

That's odd, with WINE I'm *only* able to connect using `--ipv4`...

> MSYS2

Try now. 9d9379d222d79bc3eda5d8c887076457c6182673 fixes a crash hit when using mingw.

**Comment by rcelyte** [comment]
Apparently on Windows the server needs to explicitly request IPv6 dual stack support o_0
