### ISSUE TITLE
unable to compile because of this error

### ISSUE THREAD

**Issue by keganpowers34** [rcelyte/BeatUpRcelyte#3]
src/log.h:30:1: error: expected identifier or ‘(’ before ‘[’ token
   30 | [[maybe_unused]] static void uprintf(const char *format, ...) {

gen.c:174:1: error: expected identifier or ‘(’ before ‘[’ token
  174 | [[nodiscard]] static const char *parse_struct_fields(const char *it, uint32_t indent, bool insideSwitch) {

gen.c:229:1: error: expected identifier or ‘(’ before ‘[’ token
  229 | [[nodiscard]] static const char *parse_struct(const char *it) {

gen.c:244:1: error: expected identifier or ‘(’ before ‘[’ token
  244 | [[nodiscard]] static const char *parse_enum(const char *it) {

**Comment by rcelyte** [comment]
What compiler are you using? What operating system are you on?

**Comment by keganpowers34** [comment]
i am using make and i am on ubuntus latest version

**Comment by rcelyte** [comment]
What does `cc --version` return?

**Comment by keganpowers34** [comment]
cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by rcelyte** [comment]
Your compiler is too old. I would suggest installing Clang and building with `make CC=clang NATIVE_CC=clang`

**Comment by keganpowers34** [comment]
I git pulled and ran the command and it rans successfully thank you
