### ISSUE TITLE
Will not compile 

### ISSUE THREAD

**Issue by jabberjabberjabber** [rcelyte/BeatUpRcelyte#6]
Windows fixes added yesterday seem to have broken ability to compile, at least under red hat (alma). 

$ gcc --version
gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make
[cc gen.x86_64]
Submodule 'mbedtls' (https://github.com/ARMmbed/mbedtls.git) registered for path 'mbedtls'
Cloning into '/home/frodo/rc-1/BeatUpRcelyte/mbedtls'...
[gen packets.gen.h]
Submodule path 'mbedtls': checked out '869298bffeea13b205343361b7a7daf2b210e33d'
[cc config.c.o]
[cc encryption.c.o]
[cc main.c.o]
[cc net.c.o]
[cc packets.c.o]
[cc ssl.c.o]
[cc wire.c.o]
[cc common.c.o]
[cc instance.c.o]
[cc master.c.o]
[cc pool.c.o]
[cc internal.c.o]
[cc status.c.o]
[cc status_ssl.c.o]
[make libmbedtls.a]
[make libmbedx509.a]
[make libmbedcrypto.a]
  CC    debug.c
  CC    net_sockets.c
  CC    x509.c
  CC    ssl_cache.c
  CC    x509_create.c
  CC    x509_crl.c
  CC    aes.c
  CC    ssl_ciphersuites.c
  CC    aesni.c
  CC    ssl_client.c
  CC    x509_crt.c
  CC    aria.c
  CC    ssl_cookie.c
  CC    x509_csr.c
  CC    asn1parse.c
  CC    x509write_crt.c
  CC    ssl_msg.c
  CC    asn1write.c
  CC    x509write_csr.c
  CC    ssl_ticket.c
  CC    ssl_tls.c
  CC    base64.c
  CC    bignum.c
  CC    ssl_tls12_client.c
  CC    ssl_tls12_server.c
  CC    ssl_tls13_keys.c
  CC    camellia.c
  CC    ccm.c
  CC    chacha20.c
  CC    ssl_tls13_client.c
  CC    ssl_tls13_server.c
  CC    chachapoly.c
  CC    cipher.c
  CC    ssl_tls13_generic.c
  CC    cipher_wrap.c
  CC    cmac.c
  CC    constant_time.c
  CC    ctr_drbg.c
  CC    des.c
  CC    dhm.c
  CC    ecdh.c
  CC    ecdsa.c
  CC    ecjpake.c
  CC    ecp.c
  CC    ecp_curves.c
  CC    entropy.c
  CC    entropy_poll.c
  Gen   error.c
  CC    gcm.c
  CC    hkdf.c
  CC    hmac_drbg.c
  CC    md.c
  CC    md5.c
  CC    memory_buffer_alloc.c
  CC    mps_reader.c
  CC    mps_trace.c
  CC    nist_kw.c
  CC    oid.c
  CC    padlock.c
  CC    pem.c
  CC    pk.c
  CC    pk_wrap.c
  CC    pkcs12.c
  AR    libmbedx509.a
  CC    pkcs5.c
  CC    pkparse.c
  CC    pkwrite.c
  CC    platform.c
  CC    platform_util.c
  CC    poly1305.c
  CC    psa_crypto.c
  CC    psa_crypto_aead.c
  CC    psa_crypto_cipher.c
  CC    psa_crypto_client.c
  Gen   psa_crypto_driver_wrappers.c
  CC    psa_crypto_ecp.c
  CC    psa_crypto_hash.c
  CC    psa_crypto_mac.c
  CC    psa_crypto_rsa.c
  CC    psa_crypto_se.c
  CC    psa_crypto_slot_management.c
  CC    psa_crypto_storage.c
  CC    psa_its_file.c
  CC    ripemd160.c
  CC    rsa.c
  CC    rsa_alt_helpers.c
  CC    sha1.c
  CC    sha256.c
  CC    sha512.c
  Gen   ssl_debug_helpers_generated.c
  CC    threading.c
  CC    timing.c
  CC    version.c
  Gen   version_features.c
  CC    ../3rdparty/everest/library/everest.c
  CC    ../3rdparty/everest/library/x25519.c
  CC    ../3rdparty/everest/library/Hacl_Curve25519_joined.c
  CC    error.c
  CC    psa_crypto_driver_wrappers.c
  CC    ssl_debug_helpers_generated.c
  CC    version_features.c
  AR    libmbedtls.a
  AR    libmbedcrypto.a
[cc beatupserver]
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_bases':
(.text+0x1acd): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info':
(.text+0x1b87): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_table_bases':
(.text+0x1c5c): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_table':
(.text+0x1cf4): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_table':
(.text+0x1da1): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o):(.text+0x1e32): more undefined references to `pthread_mutex_lock' follow
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__deregister_frame_info_bases':
(.text+0x1e7a): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: (.text+0x1efd): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `_Unwind_Find_FDE':
(.text+0x2024): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: (.text+0x2180): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: (.text+0x21bc): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_bases':
(.text+0x1b00): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info':
(.text+0x1bba): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o): in function `__register_frame_info_table_bases':
(.text+0x1c8f): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: /opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11/libgcc_eh.a(unwind-dw2-fde-dip.o):(.text+0x1d27): more undefined references to `pthread_mutex_unlock' follow
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/net.c.o: in function `net_init':
net.c:(.text+0x231a): undefined reference to `pthread_mutexattr_init'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: net.c:(.text+0x2332): undefined reference to `pthread_mutexattr_settype'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: net.c:(.text+0x2353): undefined reference to `pthread_mutex_init'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/net.c.o: in function `net_cleanup':
net.c:(.text+0x2c48): undefined reference to `pthread_mutex_destroy'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/net.c.o: in function `net_lock':
net.c:(.text+0x2cd8): undefined reference to `pthread_mutex_trylock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: net.c:(.text+0x2cfb): undefined reference to `pthread_mutex_lock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/net.c.o: in function `net_unlock':
net.c:(.text+0x2d1c): undefined reference to `pthread_mutex_unlock'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/instance/instance.c.o: in function `instance_init':
instance.c:(.text+0xf100): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/instance/instance.c.o: in function `instance_cleanup':
instance.c:(.text+0xf210): undefined reference to `pthread_join'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/master/master.c.o: in function `master_init':
master.c:(.text+0x4c55): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/master/master.c.o: in function `master_cleanup':
master.c:(.text+0x4caf): undefined reference to `pthread_join'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status.c.o: in function `status_handler':
status.c:(.text+0x180e): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status.c.o: in function `status_init':
status.c:(.text+0x18a2): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status.c.o: in function `status_cleanup':
status.c:(.text+0x1926): undefined reference to `pthread_join'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status_ssl.c.o: in function `status_ssl_handler':
status_ssl.c:(.text+0x1976): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status_ssl.c.o: in function `status_ssl_init':
status_ssl.c:(.text+0x1c07): undefined reference to `pthread_create'
/opt/rh/gcc-toolset-11/root/usr/bin/ld: .obj/x86_64-redhat-linux/src/status/status_ssl.c.o: in function `status_ssl_cleanup':
status_ssl.c:(.text+0x1cad): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make: *** [makefile:29: beatupserver] Error 1

**Comment by rcelyte** [comment]
Whoops. Should be fixed now.

**Comment by jabberjabberjabber** [comment]
Yeah that did it
